[parity]
chain = "./spec/spec.json"
base_path = "./nodes/validator/"

[network]
port = 40400
discovery = true
reserved_peers = "./nodes/reserved_peers"

[account]
unlock = [""]
password = ["password"]

[mining]
force_sealing = true
engine_signer = ""
reseal_on_txs = "none"

[rpc]
cors = ["all"]
hosts = ["all"]
port = 3545
interface = "all"
apis = ["web3", "eth", "net", "personal", "parity", "parity_set", "traces", "rpc", "parity_accounts"]

[footprint]
tracing = "on"
pruning = "archive"
fat_db = "on"

